# Generated by Django 3.1.7 on 2021-07-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
