# Generated by Django 3.1.7 on 2021-11-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_user', '0002_auto_20211103_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='receipt_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_for_user.goodsreceiptdetail'),
        ),
    ]
