# Generated by Django 3.1.7 on 2021-07-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_user', '0005_auto_20210717_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billdetail',
            name='bill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_for_user.bill', verbose_name='Bill'),
        ),
        migrations.AlterField(
            model_name='billdetail',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app_for_user.stock', verbose_name='Product'),
        ),
    ]
