# Generated by Django 3.1.7 on 2021-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_user', '0007_bill_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
